name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.16.0
      - name: Dependencies
        run: npm ci
      - name: Lint
        run: npm run lint
      - name: Solidity Lint
        run: npm run solhint
      - name: Solidity Compile
        run: npx hardhat compile
      - name: Solidity Tests
        run: npx hardhat test
